query getAllFeatures($filterArray: [String]) {
  features(where: { slug_not_in: $filterArray }) {
    ...FeatureSummary
  }
}

query getFeature($slug: String!) {
  feature(where: { slug: $slug }) {
    ...FeatureSummary
  }
}

query getAllFeaturesSlugs($filterArray: [String]) {
  features(where: { slug_not_in: $filterArray }) {
    slug
  }
}
